export const playListAPI: any[] = [
      {
            key: '1',
            name: 'Top ca khúc 2021',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Cindy Cường',
      },
      {
            key: '2',
            name: 'Top USUK 2020',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Grady Phùng',
      },
      {
            key: '3',
            name: 'Top EDM',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Viola Khang',
      },
      {
            key: '4',
            name: 'Top USUK',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Rene Hiền',
      },
      {
            key: '5',
            name: 'Top Korea 2021',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Yvette Đỗ',
      },
      {
            key: '6',
            name: 'Top Vpop 2021',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Cedric Hoàng',
      },
      {
            key: '7',
            name: 'Top nhạc Hoa lời Việt',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Noel Dung',
      },
      {
            key: '8',
            name: 'Top play 2020',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Adrienne Nhung',
      },
      {
            key: '9',
            name: 'Top nhạc Hoa lời Việt 2020',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Adrienne Lư',
      },
      {
            key: '10',
            name: 'Top nhạc Hoa lời Việt 2020',
            quantityRecord: Math.floor(Math.random() * 20),
            duration: Math.floor(Math.random() * 4000) + 3000,
            titles: ['Pop', 'Chill', 'Trending', 'Songs'],
            createAt: 1875938900000,
            creator: 'Adrienne Lư',
      },
];
