export const recordStoreAPI: any[] = [
      {
            name: 'Hãy trao cho anh',
            id_ISRC: 'KRA40105463',
            duration: 263,
            singer: 'Sơn Tùng M-TP',
            author: 'Sơn Tùng M-TP',
            type: 'POP',
            format: 'Audio',
            timeValid: 886405699000,
            img: 'https://th.bing.com/th/id/OIP.azbFJe2Bhci2tvGEeyECWAHaHa?pid=ImgDet&rs=1',
            linkYoutube: 'https://www.youtube.com/embed/knW7-x7Y7RE',
      },
      {
            name: 'Hạ cánh',
            id_ISRC: 'KRA40105464',
            duration: 228,
            singer: 'AFRAID x CHARIOT',
            author: 'AFRAID x CHARIOT',
            type: 'EDM',
            format: 'Audio',
            timeValid: 1886405699000,
            linkYoutube: 'https://www.youtube.com/embed/uDHAWnqzGLc',
            img: 'https://i.ytimg.com/vi/KfYfFeIyweo/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGEYgQih_MA8=&rs=AOn4CLCX2McLWXaqY18oGftTDpub4oXOyQ',
      },
      {
            name: 'Phụ tình',
            id_ISRC: 'KRA40106918',
            duration: 427,
            singer: 'Trịnh Đình Quang',
            author: 'Trịnh Đình Quang',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'https://www.youtube.com/embed/d8rXacGdR_4?list=RDd8rXacGdR_4',
            img: 'https://th.bing.com/th/id/OIP.w0oLBxS-KE-lKDLOl1ALcAHaEK?pid=ImgDet&rs=1',
      },

      {
            name: 'Handcrafted Granite ',
            id_ISRC: 'KRA40105953',
            duration: 276,
            singer: 'Vũ Cát Tường',
            author: 'Vũ Trọng Phụng',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1003456010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010509',
            duration: 295,
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010501',
            duration: 125,
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010506',
            duration: 400,
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010502',
            duration: 264,
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010503',
            duration: 264,
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
];
