export const recordStoreAPI: any[] = [
      {
            name: 'Đánh mất em',
            id_ISRC: 'KRA40105463',
            duration: '04:13',
            singer: 'Phan Mạnh Quỳnh',
            author: 'Phan Mạnh Quỳnh',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            img: 'https://source.unsplash.com/random/500x500?sig=1002903010',
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
      },
      {
            name: 'Ergonomic Fresh Chips',
            id_ISRC: 'KRA40105464',
            duration: '05:08',
            singer: 'Chillies',
            author: 'Chillies',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 1886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=d8rXacGdR_4&list=RDd8rXacGdR_4&start_radio=1',
            img: 'https://source.unsplash.com/random/500x500?sig=1001234010',
      },
      {
            name: 'Awesome Metal Salad',
            id_ISRC: 'KRA40106918',
            duration: '04:13',
            singer: 'Đen Vâu',
            author: 'Đen Vâu',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1002345010',
      },
      {
            name: 'Handcrafted Granite ',
            id_ISRC: 'KRA40105953',
            duration: '04:13',
            singer: 'Vũ Cát Tường',
            author: 'Vũ Trọng Phụng',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1003456010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010509',
            duration: '04:13',
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010501',
            duration: '04:13',
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010506',
            duration: '04:13',
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
      {
            name: 'Sleek Granite Ball ',
            id_ISRC: 'KRA4010502',
            duration: '04:13',
            singer: 'Min',
            author: 'Min',
            type: 'Ballad',
            format: 'Audio',
            timeValid: 886405699000,
            linkYoutube: 'http://www.youtube.com/watch?v=knW7-x7Y7RE',
            img: 'https://source.unsplash.com/random/500x500?sig=1004567010',
      },
];
